/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MigosAiVideoRouteImport } from './routes/migos-ai-video'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiCreemWebhookRouteImport } from './routes/api.creem.webhook'
import { Route as ApiDownloadTaskIdRouteImport } from './routes/api.download.$taskId'
import { Route as ApiHandoffTokenRouteImport } from './routes/api.handoff.$token'
import { Route as ApiWaffoWebhookRouteImport } from './routes/api.waffo.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MigosAiVideoRoute = MigosAiVideoRouteImport.update({
  id: '/migos-ai-video',
  path: '/migos-ai-video',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreemWebhookRoute = ApiCreemWebhookRouteImport.update({
  id: '/api/creem/webhook',
  path: '/api/creem/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadTaskIdRoute = ApiDownloadTaskIdRouteImport.update({
  id: '/api/download/$taskId',
  path: '/api/download/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffTokenRoute = ApiHandoffTokenRouteImport.update({
  id: '/api/handoff/$token',
  path: '/api/handoff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaffoWebhookRoute = ApiWaffoWebhookRouteImport.update({
  id: '/api/waffo/webhook',
  path: '/api/waffo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/migos-ai-video': typeof MigosAiVideoRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/creem/webhook': typeof ApiCreemWebhookRoute
  '/api/download/$taskId': typeof ApiDownloadTaskIdRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRoute
  '/api/waffo/webhook': typeof ApiWaffoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/migos-ai-video': typeof MigosAiVideoRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/creem/webhook': typeof ApiCreemWebhookRoute
  '/api/download/$taskId': typeof ApiDownloadTaskIdRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRoute
  '/api/waffo/webhook': typeof ApiWaffoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/migos-ai-video': typeof MigosAiVideoRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/creem/webhook': typeof ApiCreemWebhookRoute
  '/api/download/$taskId': typeof ApiDownloadTaskIdRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRoute
  '/api/waffo/webhook': typeof ApiWaffoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/migos-ai-video'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/callback'
    | '/api/creem/webhook'
    | '/api/download/$taskId'
    | '/api/handoff/$token'
    | '/api/waffo/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/migos-ai-video'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/callback'
    | '/api/creem/webhook'
    | '/api/download/$taskId'
    | '/api/handoff/$token'
    | '/api/waffo/webhook'
  id:
    | '__root__'
    | '/'
    | '/migos-ai-video'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/callback'
    | '/api/creem/webhook'
    | '/api/download/$taskId'
    | '/api/handoff/$token'
    | '/api/waffo/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MigosAiVideoRoute: typeof MigosAiVideoRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiCreemWebhookRoute: typeof ApiCreemWebhookRoute
  ApiDownloadTaskIdRoute: typeof ApiDownloadTaskIdRoute
  ApiHandoffTokenRoute: typeof ApiHandoffTokenRoute
  ApiWaffoWebhookRoute: typeof ApiWaffoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migos-ai-video': {
      id: '/migos-ai-video'
      path: '/migos-ai-video'
      fullPath: '/migos-ai-video'
      preLoaderRoute: typeof MigosAiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creem/webhook': {
      id: '/api/creem/webhook'
      path: '/api/creem/webhook'
      fullPath: '/api/creem/webhook'
      preLoaderRoute: typeof ApiCreemWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$taskId': {
      id: '/api/download/$taskId'
      path: '/api/download/$taskId'
      fullPath: '/api/download/$taskId'
      preLoaderRoute: typeof ApiDownloadTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoff/$token': {
      id: '/api/handoff/$token'
      path: '/api/handoff/$token'
      fullPath: '/api/handoff/$token'
      preLoaderRoute: typeof ApiHandoffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waffo/webhook': {
      id: '/api/waffo/webhook'
      path: '/api/waffo/webhook'
      fullPath: '/api/waffo/webhook'
      preLoaderRoute: typeof ApiWaffoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MigosAiVideoRoute: MigosAiVideoRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiCreemWebhookRoute: ApiCreemWebhookRoute,
  ApiDownloadTaskIdRoute: ApiDownloadTaskIdRoute,
  ApiHandoffTokenRoute: ApiHandoffTokenRoute,
  ApiWaffoWebhookRoute: ApiWaffoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
